export const allMSAs = [
  "Springfield, MA", "Greenfield, MA", "Amherst Town-Northampton, MA", "Worcester, MA", "Pittsfield, MA",
  "Boston-Cambridge-Newton, MA-NH", "Providence-Warwick, RI-MA", "Barnstable Town, MA", "Vineyard Haven, MA",
  "Nantucket, MA", "Manchester-Nashua, NH", "Concord, NH", "Lebanon-Claremont, NH-VT", "Laconia, NH",
  "Carroll County-Rural", "Keene, NH", "Coos County-Rural", "Oxford County-Rural", "Portland-South Portland, ME",
  "Lewiston-Auburn, ME", "Franklin County-Rural", "Augusta-Waterville, ME", "Lincoln County-Rural",
  "Waldo County-Rural", "Bangor, ME", "Piscataquis County-Rural", "Hancock County-Rural", "Washington County-Rural",
  "Aroostook County-Rural", "Somerset County-Rural", "Knox County-Rural", "Caledonia County-Rural", "Barre, VT",
  "Brattleboro, VT", "Bennington, VT", "Rutland, VT", "Burlington-South Burlington, VT", "Lamoille County-Rural",
  "Addison County-Rural", "Orleans County-Rural", "Essex County-Rural", "Hartford County-Rural",
  "Litchfield County-Rural", "Tolland County-Rural", "Windham County-Rural", "New London County-Rural",
  "New York-Newark-Jersey City, NY-NJ", "New Haven County-Rural", "Middlesex County-Rural", "Fairfield County-Rural",
  "Allentown-Bethlehem-Easton, PA-NJ", "Philadelphia-Camden-Wilmington, PA-NJ-DE-MD", "Atlantic City-Hammonton, NJ",
  "Vineland, NJ", "Trenton-Princeton, NJ", "Kiryas Joel-Poughkeepsie-Newburgh, NY", "Monticello, NY",
  "Albany-Schenectady-Troy, NY", "Gloversville, NY", "Amsterdam, NY", "Greene County-Rural", "Hudson, NY",
  "Glens Falls, NY", "Hamilton County-Rural", "Oneonta, NY", "Delaware County-Rural", "Kingston, NY",
  "Massena-Ogdensburg, NY", "Plattsburgh, NY", "Syracuse, NY", "Auburn, NY", "Chenango County-Rural", "Cortland, NY",
  "Utica-Rome, NY", "Ithaca, NY", "Watertown-Fort Drum, NY", "Rochester, NY", "Seneca Falls, NY",
  "Lewis County-Rural", "Binghamton, NY", "Buffalo-Cheektowaga, NY", "Batavia, NY", "Wyoming County-Rural",
  "Olean, NY", "Allegany County-Rural", "Jamestown-Dunkirk, NY", "Yates County-Rural", "Corning, NY",
  "Schuyler County-Rural", "Elmira, NY", "Pittsburgh, PA", "Somerset, PA", "Bedford County-Rural",
  "Fulton County-Rural", "Indiana, PA", "Jefferson County-Rural", "Johnstown, PA", "DuBois, PA", "St. Marys, PA",
  "Forest County-Rural", "Clarion County-Rural", "Cameron County-Rural", "Bradford, PA", "Altoona, PA",
  "Oil City, PA", "Hermitage, PA", "Meadville, PA", "Warren, PA", "Erie, PA", "Huntingdon, PA", "State College, PA",
  "Potter County-Rural", "Lock Haven, PA", "Tioga County-Rural", "Sayre, PA", "Williamsport, PA", "Lewistown, PA",
  "Lebanon, PA", "Harrisburg-Carlisle, PA", "York-Hanover, PA", "Sunbury, PA", "Gettysburg, PA",
  "Chambersburg, PA", "Juniata County-Rural", "Lancaster, PA", "Reading, PA", "Selinsgrove, PA",
  "Sullivan County-Rural", "Bloomsburg-Berwick, PA", "Lewisburg, PA", "Scranton--Wilkes-Barre, PA", "Pottsville, PA",
  "East Stroudsburg, PA", "Hemlock Farms, PA", "Wayne County-Rural", "Susquehanna County-Rural", "Dover, DE",
  "Seaford, DE", "Washington-Arlington-Alexandria, DC-VA-MD-WV", "Lexington Park, MD",
  "Baltimore-Columbia-Towson, MD", "Cumberland, MD-WV", "Garrett County-Rural", "Easton, MD", "Kent County-Rural",
  "Cambridge, MD", "Caroline County-Rural", "Hagerstown-Martinsburg, MD-WV", "Salisbury, MD", "Ocean Pines, MD",
  "Northumberland County-Rural", "Lake of the Woods, VA", "Richmond County-Rural", "Westmoreland County-Rural",
  "Richmond, VA", "King George County-Rural", "Lancaster County-Rural", "Winchester, VA-WV",
  "Shenandoah County-Rural", "Page County-Rural", "Madison County-Rural", "Harrisonburg, VA",
  "Staunton-Stuarts Draft, VA", "Charlottesville, VA", "Lynchburg, VA", "Louisa County-Rural",
  "Nottoway County-Rural", "Buckingham County-Rural", "Virginia Beach-Chesapeake-Norfolk, VA-NC",
  "Cumberland County-Rural", "Accomack County-Rural", "Northampton County-Rural", "Brunswick County-Rural",
  "Lunenburg County-Rural", "Southampton County-Rural", "Greensville County-Rural", "Emporia city-Rural",
  "Franklin city-Rural", "Prince Edward County-Rural", "Mecklenburg County-Rural", "Charlotte County-Rural",
  "Halifax County-Rural", "Roanoke, VA", "Patrick County-Rural", "Martinsville, VA", "Danville, VA",
  "Blacksburg-Christiansburg-Radford, VA", "Rockbridge County-Rural", "Bland County-Rural",
  "Alleghany County-Rural", "Kingsport-Bristol, TN-VA", "Wise County-Rural", "Buchanan County-Rural",
  "Dickenson County-Rural", "Lee County-Rural", "Russell County-Rural", "Norton city-Rural", "Grayson County-Rural",
  "Smyth County-Rural", "Wythe County-Rural", "Bluefield, WV-VA", "Galax city-Rural", "Bath County-Rural",
  "Highland County-Rural", "Buena Vista city-Rural", "Covington city-Rural", "Lexington city-Rural",
  "Bedford city-Rural", "McDowell County-Rural", "Mingo County-Rural", "Greenbrier County-Rural",
  "Monroe County-Rural", "Summers County-Rural", "Pocahontas County-Rural", "Beckley, WV", "Charleston, WV",
  "Roane County-Rural", "Huntington-Ashland, WV-KY-OH", "Logan County-Rural", "Nicholas County-Rural",
  "Braxton County-Rural", "Mason County-Rural", "Jackson County-Rural", "Calhoun County-Rural",
  "Parkersburg-Vienna, WV", "Gilmer County-Rural", "Weirton-Steubenville, WV-OH", "Wheeling, WV-OH",
  "Wetzel County-Rural", "Pleasants County-Rural", "Ritchie County-Rural", "Tyler County-Rural",
  "Barbour County-Rural", "Upshur County-Rural", "Webster County-Rural", "Elkins, WV", "Tucker County-Rural",
  "Clarksburg, WV", "Fairmont, WV", "Morgantown, WV", "Grant County-Rural", "Hardy County-Rural",
  "Pendleton County-Rural", "Winston-Salem, NC", "Mount Airy, NC", "Charlotte-Concord-Gastonia, NC-SC",
  "North Wilkesboro, NC", "Greensboro-High Point, NC", "Burlington, NC", "Durham-Chapel Hill, NC",
  "Pinehurst-Southern Pines, NC", "Montgomery County-Rural", "Caswell County-Rural", "Rockingham, NC",
  "Anderson Creek, NC", "Sanford, NC", "Raleigh-Cary, NC", "Granville County-Rural", "Henderson, NC",
  "Goldsboro, NC", "Warren County-Rural", "Wilson, NC", "Rocky Mount, NC", "Bertie County-Rural",
  "Hertford County-Rural", "Washington, NC", "Hyde County-Rural", "Martin County-Rural", "Greenville, NC",
  "Roanoke Rapids, NC", "Tyrrell County-Rural", "Elizabeth City, NC", "Kill Devil Hills, NC",
  "Chowan County-Rural", "Perquimans County-Rural", "Albemarle, NC", "Shelby-Kings Mountain, NC", "Forest City, NC",
  "Hickory-Lenoir-Morganton, NC", "Polk County-Rural", "Marion, NC", "Fayetteville, NC", "Bladen County-Rural",
  "Sampson County-Rural", "Columbus County-Rural", "Duplin County-Rural", "Lumberton, NC", "Laurinburg, NC",
  "Wilmington, NC", "Jacksonville, NC", "New Bern, NC", "Kinston, NC", "Morehead City, NC", "Avery County-Rural",
  "Boone, NC", "Ashe County-Rural", "Asheville, NC", "Graham County-Rural", "Swain County-Rural",
  "Mitchell County-Rural", "Brevard, NC", "Yancey County-Rural", "Waynesville, NC", "Macon County-Rural",
  "Cherokee County-Rural", "Clay County-Rural", "Clarendon County-Rural", "Sumter, SC", "Bamberg County-Rural",
  "Augusta-Richmond County, GA-SC", "Columbia, SC", "Chesterfield County-Rural", "Charleston-North Charleston, SC",
  "Orangeburg, SC", "Spartanburg, SC", "Newberry, SC", "Williamsburg County-Rural", "Florence, SC",
  "Colleton County-Rural", "Greenwood, SC", "Greenville-Anderson-Greer, SC", "Gaffney, SC",
  "Murrells Inlet, SC", "Myrtle Beach-Conway-North Myrtle Beach, SC", "Marlboro County-Rural",
  "Marion County-Rural", "Dillon County-Rural", "McCormick County-Rural", "Seneca, SC", "Allendale County-Rural",
  "Barnwell County-Rural", "Hilton Head Island-Bluffton-Port Royal, SC", "Hampton County-Rural",
  "Atlanta-Sandy Springs-Roswell, GA", "Rome, GA", "Calhoun, GA", "Cedartown, GA", "Summerville, GA",
  "Lamar County-Rural", "Macon-Bibb County, GA", "Thomaston, GA", "LaGrange, GA-AL", "Emanuel County-Rural",
  "Vidalia, GA", "Dublin, GA", "Telfair County-Rural", "Wheeler County-Rural", "Statesboro, GA",
  "Tattnall County-Rural", "Candler County-Rural", "Jenkins County-Rural", "Screven County-Rural", "Hinesville, GA",
  "Savannah, GA", "Treutlen County-Rural", "Gainesville, GA", "Banks County-Rural", "Cornelia, GA", "Toccoa, GA",
  "Fannin County-Rural", "Union County-Rural", "Hart County-Rural", "Jefferson, GA", "Rabun County-Rural",
  "White County-Rural", "Athens-Clarke County, GA", "Towns County-Rural", "Elbert County-Rural",
  "Putnam County-Rural", "Taliaferro County-Rural", "Wilkes County-Rural", "Dalton, GA", "Chattanooga, TN-GA",
  "Glascock County-Rural", "Wilcox County-Rural", "Wilkinson County-Rural", "Warner Robins, GA",
  "Taylor County-Rural", "Dooly County-Rural", "Dodge County-Rural", "Bleckley County-Rural", "Cordele, GA",
  "Pulaski County-Rural", "Milledgeville, GA", "Columbus, GA-AL", "Fitzgerald, GA", "Brunswick-St. Simons, GA",
  "Waycross, GA", "Bacon County-Rural", "Jeff Davis County-Rural", "Douglas, GA", "Appling County-Rural",
  "Jesup, GA", "Kingsland, GA", "Charlton County-Rural", "Valdosta, GA", "Cook County-Rural",
  "Berrien County-Rural", "Clinch County-Rural", "Thomasville, GA", "Moultrie, GA", "Tifton, GA", "Albany, GA",
  "Americus, GA", "Baker County-Rural", "Bainbridge, GA", "Irwin County-Rural", "Jacksonville, FL",
  "Dixie County-Rural", "Gainesville, FL", "Lafayette County-Rural", "Suwannee County-Rural", "Lake City, FL",
  "Bradford County-Rural", "Palatka, FL", "Orlando-Kissimmee-Sanford, FL",
  "Deltona-Daytona Beach-Ormond Beach, FL", "Ocala, FL", "Wildwood-The Villages, FL", "Tallahassee, FL",
  "Liberty County-Rural", "Panama City-Panama City Beach, FL", "Crestview-Fort Walton Beach-Destin, FL",
  "Holmes County-Rural", "Gulf County-Rural", "Pensacola-Ferry Pass-Brent, FL",
  "Palm Bay-Melbourne-Titusville, FL", "Sebastian-Vero Beach-West Vero Corridor, FL", "Key West-Key Largo, FL",
  "Miami-Fort Lauderdale-West Palm Beach, FL", "Port St. Lucie, FL", "Clewiston, FL",
  "Tampa-St. Petersburg-Clearwater, FL", "North Port-Bradenton-Sarasota, FL", "Lakeland-Winter Haven, FL",
  "Hardee County-Rural", "Sebring, FL", "Cape Coral-Fort Myers, FL", "Punta Gorda, FL", "Naples-Marco Island, FL",
  "Arcadia, FL", "Homosassa Springs, FL", "Okeechobee, FL", "Birmingham, AL", "Tuscaloosa, AL",
  "Talladega-Sylacauga, AL", "Montgomery, AL", "Alexander City, AL", "Cullman, AL", "Albertville, AL",
  "Decatur, AL", "Perry County-Rural", "Winston County-Rural", "Anniston-Oxford, AL", "Sumter County-Rural",
  "Fayette County-Rural", "Russellville, AL", "Florence-Muscle Shoals, AL", "Huntsville, AL", "Scottsboro, AL",
  "Fort Payne, AL", "Gadsden, AL", "Eufaula, AL-GA", "Bullock County-Rural", "Troy, AL", "Enterprise, AL",
  "Crenshaw County-Rural", "Ozark, AL", "Dothan, AL", "Covington County-Rural", "Auburn-Opelika, AL",
  "Butler County-Rural", "Conecuh County-Rural", "Cleburne County-Rural", "Randolph County-Rural",
  "Escambia County-Rural", "Clarke County-Rural", "Daphne-Fairhope-Foley, AL", "Mobile, AL",
  "Choctaw County-Rural", "Selma, AL", "Marengo County-Rural", "Clarksville, TN-KY",
  "Nashville-Davidson--Murfreesboro--Franklin, TN", "DeKalb County-Rural", "Shelbyville, TN",
  "Tullahoma-Manchester, TN", "Lewisburg, TN", "Giles County-Rural", "Fayetteville, TN", "Houston County-Rural",
  "Humphreys County-Rural", "Grundy County-Rural", "Van Buren County-Rural", "McMinnville, TN", "Cookeville, TN",
  "Athens, TN", "Winchester, TN", "Cleveland, TN", "Bledsoe County-Rural", "Rhea County-Rural", "Crossville, TN",
  "Johnson City, TN", "Greeneville, TN", "Johnson County-Rural", "Knoxville, TN", "Morristown, TN", "Newport, TN",
  "Claiborne County-Rural", "Sevierville, TN", "Fentress County-Rural", "Scott County-Rural", "Jackson, TN",
  "Memphis, TN-MS-AR", "Haywood County-Rural", "Dyersburg, TN", "Hardeman County-Rural", "Lauderdale County-Rural",
  "McNairy County-Rural", "Lake County-Rural", "Union City, TN", "Paris, TN", "Martin, TN", "Benton County-Rural",
  "Hardin County-Rural", "Decatur County-Rural", "Henderson County-Rural", "Tishomingo County-Rural",
  "Lawrenceburg, TN", "Pickett County-Rural", "Oxford, MS", "Tippah County-Rural", "Panola County-Rural",
  "Quitman County-Rural", "Cleveland, MS", "Clarksdale, MS", "Tallahatchie County-Rural", "Corinth, MS",
  "Greenville, MS", "Issaquena County-Rural", "Sharkey County-Rural", "Sunflower County-Rural", "Greenwood, MS",
  "Desha County-Rural", "Tupelo, MS", "Pontotoc County-Rural", "Chickasaw County-Rural", "Grenada, MS",
  "Starkville, MS", "Jackson, MS", "Smith County-Rural", "Attala County-Rural", "Leake County-Rural",
  "Neshoba County-Rural", "Newton County-Rural", "Natchez, MS-LA", "Jefferson Davis County-Rural",
  "Lawrence County-Rural", "Vicksburg, MS", "Laurel, MS", "Brookhaven, MS", "Meridian, MS", "Kemper County-Rural",
  "Columbus, MS", "Hattiesburg, MS", "Gulfport-Biloxi, MS", "Picayune, MS", "George County-Rural", "McComb, MS",
  "Amite County-Rural", "Early County-Rural", "Miller County-Rural", "Seminole County-Rural", "Frankfort, KY",
  "Louisville/Jefferson County, KY-IN", "Trimble County-Rural", "Campbellsville, KY", "Elizabethtown, KY",
  "Breckinridge County-Rural", "Ohio County-Rural", "Mercer County-Rural", "Lexington-Fayette, KY",
  "Robertson County-Rural", "Powell County-Rural", "Rowan County-Rural", "Mount Sterling, KY", "Danville, KY",
  "Casey County-Rural", "Richmond-Berea, KY", "Elliott County-Rural", "Owen County-Rural", "Harrison County-Rural",
  "Morgan County-Rural", "Garrard County-Rural", "Somerset, KY", "Owsley County-Rural", "Corbin, KY",
  "McCreary County-Rural", "Harlan County-Rural", "Leslie County-Rural", "Middlesborough, KY",
  "Letcher County-Rural", "Cincinnati, OH-KY-IN", "Fleming County-Rural", "Pikeville, KY",
  "Breathitt County-Rural", "Wolfe County-Rural", "Knott County-Rural", "Magoffin County-Rural", "Paducah, KY-IL",
  "Murray, KY", "Hickman County-Rural", "Mayfield, KY", "Marshall County-Rural", "Crittenden County-Rural",
  "Caldwell County-Rural", "Lyon County-Rural", "Bowling Green, KY", "Franklin, KY", "Glasgow, KY",
  "Adair County-Rural", "Todd County-Rural", "Muhlenberg County-Rural", "Owensboro, KY", "Henderson, KY",
  "Madisonville, KY", "Clinton County-Rural", "Columbus, OH", "Mount Vernon, OH", "Coshocton, OH", "Urbana, OH",
  "Springfield, OH", "Mansfield, OH", "Bellefontaine, OH", "Chillicothe, OH", "Washington Court House, OH",
  "Vinton County-Rural", "Dayton-Kettering-Beavercreek, OH", "Bucyrus, OH", "Marion, OH", "Findlay, OH",
  "Tiffin, OH", "Wyandot County-Rural", "Wapakoneta, OH", "Toledo, OH", "Fremont, OH", "Sandusky, OH",
  "Williams County-Rural", "Henry County-Rural", "Defiance, OH", "Paulding County-Rural", "Zanesville, OH",
  "Noble County-Rural", "Cambridge, OH", "Athens, OH", "New Philadelphia-Dover, OH", "Marietta, OH",
  "Canton-Massillon, OH", "Salem, OH", "Cleveland, OH", "Akron, OH", "Youngstown-Warren, OH", "Wooster, OH",
  "Ashland, OH", "Norwalk, OH", "Preble County-Rural", "Wilmington, OH", "Pike County-Rural", "Adams County-Rural",
  "Sidney, OH", "Greenville, OH", "Celina, OH", "Portsmouth, OH", "Gallipolis, OH", "Meigs County-Rural",
  "Lima, OH", "Van Wert, OH", "Muncie, IN", "Indianapolis-Carmel-Greenwood, IN", "Frankfort, IN",
  "Crawfordsville, IN", "Marion, IN", "Lafayette-West Lafayette, IN", "Kokomo, IN", "Rush County-Rural",
  "Greencastle, IN", "New Castle, IN", "Bloomington, IN", "Columbus, IN", "Connersville, IN", "Parke County-Rural",
  "Greensburg, IN", "Chicago-Naperville-Elgin, IL-IN", "Michigan City-La Porte, IN", "Starke County-Rural",
  "Plymouth, IN", "Warsaw, IN", "South Bend-Mishawaka, IN-MI", "Elkhart-Goshen, IN", "LaGrange County-Rural",
  "Kendallville, IN", "Fort Wayne, IN", "Huntington, IN", "Wabash, IN", "Angola, IN", "Auburn, IN", "Decatur, IN",
  "Peru, IN", "Logansport, IN", "Blackford County-Rural", "Monticello, IN", "Ripley County-Rural",
  "Switzerland County-Rural", "Madison, IN", "Seymour, IN", "Orange County-Rural", "Crawford County-Rural",
  "Jennings County-Rural", "Bedford, IN", "Jay County-Rural", "Richmond, IN", "Terre Haute, IN", "Jasper, IN",
  "Washington, IN", "Vincennes, IN", "Spencer County-Rural", "Evansville, IN", "Gibson County-Rural",
  "Fountain County-Rural", "Detroit-Warren-Dearborn, MI", "Sanilac County-Rural", "Ann Arbor, MI", "Monroe, MI",
  "Jackson, MI", "Adrian, MI", "Flint, MI", "Huron County-Rural", "Owosso, MI", "Saginaw, MI",
  "Tuscola County-Rural", "Bay City, MI", "Arenac County-Rural", "Gladwin County-Rural", "Ogemaw County-Rural",
  "Midland, MI", "Alma, MI", "Clare County-Rural", "Mount Pleasant, MI", "Montmorency County-Rural",
  "Oscoda County-Rural", "Roscommon County-Rural", "Osceola County-Rural", "Alcona County-Rural",
  "Iosco County-Rural", "Alpena, MI", "Lansing-East Lansing, MI", "Grand Rapids-Wyoming-Kentwood, MI",
  "Battle Creek, MI", "Big Rapids, MI", "Kalamazoo-Portage, MI", "Holland, MI", "Coldwater, MI", "Sturgis, MI",
  "Niles, MI", "Hillsdale, MI", "Muskegon-Norton Shores, MI", "Newaygo County-Rural", "Ludington, MI",
  "Oceana County-Rural", "Cadillac, MI", "Antrim County-Rural", "Traverse City, MI", "Manistee County-Rural",
  "Cheboygan County-Rural", "Petoskey, MI", "Presque Isle County-Rural", "Sault Ste. Marie, MI",
  "Charlevoix County-Rural", "Mackinac County-Rural", "Otsego County-Rural", "Luce County-Rural",
  "Iron Mountain, MI-WI", "Houghton, MI", "Alger County-Rural", "Escanaba, MI", "Marinette, WI-MI",
  "Marquette, MI", "Schoolcraft County-Rural", "Baraga County-Rural", "Iron County-Rural", "Ontonagon County-Rural",
  "Gogebic County-Rural", "Des Moines-West Des Moines, IA", "Marshalltown, IA", "Ames, IA", "Audubon County-Rural",
  "Cass County-Rural", "Shelby County-Rural", "Oskaloosa, IA", "Poweshiek County-Rural", "Wright County-Rural",
  "Pella, IA", "Lucas County-Rural", "Carroll, IA", "Ringgold County-Rural", "Keokuk County-Rural",
  "Tama County-Rural", "Iowa County-Rural", "Fort Dodge, IA", "Mason City, IA", "Kossuth County-Rural",
  "Winnebago County-Rural", "Floyd County-Rural", "Howard County-Rural", "Storm Lake, IA", "Emmet County-Rural",
  "Spencer, IA", "Palo Alto County-Rural", "Humboldt County-Rural", "Sac County-Rural", "Waterloo-Cedar Falls, IA",
  "Clayton County-Rural", "Cedar Rapids, IA", "Le Mars, IA", "Sioux City, IA-NE-SD", "Sioux County-Rural",
  "Ida County-Rural", "O'Brien County-Rural", "Monona County-Rural", "Spirit Lake, IA", "Omaha, NE-IA",
  "Burt County-Rural", "Fremont County-Rural", "Atchison County-Rural", "Dubuque, IA", "Clinton, IA",
  "Allamakee County-Rural", "Winneshiek County-Rural", "Iowa City, IA", "Cedar County-Rural", "Ottumwa, IA",
  "Davis County-Rural", "Scotland County-Rural", "Appanoose County-Rural", "Burlington, IA-IL", "Fort Madison, IA",
  "Clark County-Rural", "Muscatine, IA", "Davenport-Moline-Rock Island, IA-IL", "Sheboygan, WI",
  "Milwaukee-Waukesha, WI", "Beaver Dam, WI", "Fond du Lac, WI", "Appleton, WI", "Manitowoc, WI",
  "Watertown-Fort Atkinson, WI", "Kenosha, WI", "Racine-Mount Pleasant, WI", "Whitewater-Elkhorn, WI",
  "Janesville-Beloit, WI", "Madison, WI", "Platteville, WI", "Richland County-Rural", "Baraboo, WI",
  "Marquette County-Rural", "Green Lake County-Rural", "Juneau County-Rural", "Sparta, WI",
  "La Crosse-Onalaska, WI-MN", "Waushara County-Rural", "Minneapolis-St. Paul-Bloomington, MN-WI", "Rice Lake, WI",
  "Menomonie, WI", "Green Bay, WI", "Shawano, WI", "Waupaca County-Rural", "Langlade County-Rural",
  "Door County-Rural", "Wausau, WI", "Stevens Point-Plover, WI", "Wisconsin Rapids-Marshfield, WI",
  "Oneida County-Rural", "Eau Claire, WI", "Price County-Rural", "Vilas County-Rural", "Ashland County-Rural",
  "Bayfield County-Rural", "Sawyer County-Rural", "Rusk County-Rural", "Buffalo County-Rural",
  "Trempealeau County-Rural", "Pepin County-Rural", "Burnett County-Rural", "Washburn County-Rural",
  "Duluth, MN-WI", "Oshkosh-Neenah, WI", "Kanabec County-Rural", "Pine County-Rural", "Red Wing, MN",
  "Faribault-Northfield, MN", "Rochester, MN", "Owatonna, MN", "Waseca County-Rural", "Sibley County-Rural",
  "Renville County-Rural", "Hutchinson, MN", "St. Cloud, MN", "Meeker County-Rural", "Mankato, MN", "New Ulm, MN",
  "Redwood County-Rural", "Grand Rapids, MN", "Aitkin County-Rural", "Koochiching County-Rural", "Brainerd, MN",
  "Austin, MN", "Winona, MN", "Albert Lea, MN", "Faribault County-Rural", "Fairmont, MN",
  "Cottonwood County-Rural", "Watonwan County-Rural", "Worthington, MN", "Murray County-Rural", "Marshall, MN",
  "Sioux Falls, SD-MN", "Pipestone County-Rural", "Moody County-Rural", "Willmar, MN", "Stevens County-Rural",
  "Swift County-Rural", "Chippewa County-Rural", "Lac qui Parle County-Rural", "Big Stone County-Rural",
  "Traverse County-Rural", "Yellow Medicine County-Rural", "Pope County-Rural", "Roberts County-Rural",
  "Alexandria, MN", "Fergus Falls, MN", "Morrison County-Rural", "Hubbard County-Rural", "Wadena County-Rural",
  "Detroit Lakes, MN", "Clearwater County-Rural", "Norman County-Rural", "Fargo, ND-MN", "Wahpeton, ND-MN",
  "Mahnomen County-Rural", "Grand Forks, ND-MN", "Red Lake County-Rural", "Bemidji, MN",
  "Lake of the Woods County-Rural", "Roseau County-Rural", "Pennington County-Rural", "Kittson County-Rural",
  "Walsh County-Rural", "Brookings, SD", "Vermillion, SD", "Hutchinson County-Rural", "Yankton, SD",
  "Kingsbury County-Rural", "Bon Homme County-Rural", "Miner County-Rural", "Watertown, SD", "Hamlin County-Rural",
  "Deuel County-Rural", "Day County-Rural", "Spink County-Rural", "Mitchell, SD", "Huron, SD",
  "Jerauld County-Rural", "Charles Mix County-Rural", "Douglas County-Rural", "Gregory County-Rural",
  "Brule County-Rural", "Aurora County-Rural", "Hand County-Rural", "Lyman County-Rural", "Aberdeen, SD",
  "Walworth County-Rural", "Faulk County-Rural", "Campbell County-Rural", "McPherson County-Rural",
  "Dewey County-Rural", "Sully County-Rural", "Pierre, SD", "Mellette County-Rural", "Tripp County-Rural",
  "Jones County-Rural", "Bennett County-Rural", "Haakon County-Rural", "Corson County-Rural", "Perkins County-Rural",
  "Ziebach County-Rural", "Rapid City, SD", "Emmons County-Rural", "Harding County-Rural", "Shannon County-Rural",
  "Butte County-Rural", "Spearfish, SD", "Crook County-Rural", "Fall River County-Rural", "Carter County-Rural",
  "Traill County-Rural", "Sargent County-Rural", "Steele County-Rural", "Barnes County-Rural",
  "Ransom County-Rural", "LaMoure County-Rural", "Griggs County-Rural", "Nelson County-Rural",
  "Pembina County-Rural", "Cavalier County-Rural", "Ramsey County-Rural", "Benson County-Rural",
  "Rolette County-Rural", "Towner County-Rural", "Bottineau County-Rural", "Pierce County-Rural",
  "Sheridan County-Rural", "Wells County-Rural", "Eddy County-Rural", "Foster County-Rural", "Minot, ND",
  "Jamestown, ND", "Dickey County-Rural", "McIntosh County-Rural", "Kidder County-Rural", "Bismarck, ND",
  "McLean County-Rural", "Hettinger County-Rural", "Dickinson, ND", "Slope County-Rural",
  "Golden Valley County-Rural", "Bowman County-Rural", "McKenzie County-Rural", "Mountrail County-Rural",
  "Burke County-Rural", "Divide County-Rural", "Williston, ND", "Billings, MT", "Powder River County-Rural",
  "Rosebud County-Rural", "Big Horn County-Rural", "Treasure County-Rural", "Sweet Grass County-Rural",
  "Musselshell County-Rural", "Park County-Rural", "Fergus County-Rural", "Petroleum County-Rural",
  "Wheatland County-Rural", "Meagher County-Rural", "Garfield County-Rural", "Bozeman, MT", "McCone County-Rural",
  "Roosevelt County-Rural", "Valley County-Rural", "Dawson County-Rural", "Daniels County-Rural",
  "Phillips County-Rural", "Custer County-Rural", "Fallon County-Rural", "Prairie County-Rural",
  "Wibaux County-Rural", "Great Falls, MT", "Chouteau County-Rural", "Helena, MT", "Teton County-Rural",
  "Glacier County-Rural", "Pondera County-Rural", "Judith Basin County-Rural", "Toole County-Rural",
  "Hill County-Rural", "Blaine County-Rural", "Butte-Silver Bow, MT", "Deer Lodge County-Rural",
  "Granite County-Rural", "Beaverhead County-Rural", "Missoula, MT", "Sanders County-Rural", "Ravalli County-Rural",
  "Kalispell, MT", "Idaho County-Rural", "Rockford, IL", "Rochelle, IL", "Kankakee, IL", "Pontiac, IL",
  "Ottawa, IL", "Dixon, IL", "Iroquois County-Rural", "Champaign-Urbana, IL", "Danville, IL", "Bloomington, IL",
  "Jo Daviess County-Rural", "Freeport, IL", "Sterling, IL", "Peoria, IL", "Galesburg, IL", "Macomb, IL",
  "Canton, IL", "Lincoln, IL", "De Witt County-Rural", "Decatur, IL", "Edgar County-Rural",
  "Charleston-Mattoon, IL", "Moultrie County-Rural", "St. Louis, MO-IL", "Taylorville, IL", "Jacksonville, IL",
  "Carbondale, IL", "Quincy, IL-MO", "Brown County-Rural", "Effingham, IL", "Wabash County-Rural",
  "Jasper County-Rural", "Edwards County-Rural", "Springfield, IL", "Mount Vernon, IL", "Centralia, IL",
  "Marion-Herrin, IL", "Gallatin County-Rural", "Saline County-Rural", "Cape Girardeau, MO-IL",
  "Gasconade County-Rural", "Ste. Genevieve County-Rural", "Farmington, MO", "Mexico, MO", "Hannibal, MO",
  "Jefferson City, MO", "Kirksville, MO", "Linn County-Rural", "Chariton County-Rural", "Reynolds County-Rural",
  "Dent County-Rural", "Stoddard County-Rural", "Sikeston, MO", "New Madrid County-Rural", "Kennett, MO",
  "Pemiscot County-Rural", "Poplar Bluff, MO", "Oregon County-Rural", "Kansas City, MO-KS", "Warrensburg, MO",
  "Marshall, MO", "St. Joseph, MO-KS", "Gentry County-Rural", "Worth County-Rural", "Maryville, MO",
  "Daviess County-Rural", "Holt County-Rural", "Livingston County-Rural", "St. Clair County-Rural",
  "Vernon County-Rural", "Barton County-Rural", "Dade County-Rural", "Joplin, MO-KS", "McDonald County-Rural",
  "Barry County-Rural", "Maries County-Rural", "Columbia, MO", "Camden County-Rural", "Moberly, MO", "Sedalia, MO",
  "Hickory County-Rural", "Rolla, MO", "Texas County-Rural", "Fort Leonard Wood, MO", "Springfield, MO",
  "Lebanon, MO", "West Plains, MO", "Ozark County-Rural", "Branson, MO", "Stone County-Rural", "Harrison, AR",
  "Atchison, KS", "Topeka, KS", "Lawrence, KS", "Ottawa, KS", "Bourbon County-Rural", "Anderson County-Rural",
  "Allen County-Rural", "Coffey County-Rural", "Nemaha County-Rural", "Manhattan, KS", "Emporia, KS",
  "Dickinson County-Rural", "Pawnee County-Rural", "Pittsburg, KS", "Wilson County-Rural", "Neosho County-Rural",
  "Elk County-Rural", "Woodson County-Rural", "Labette County-Rural", "Greenwood County-Rural",
  "Morris County-Rural", "Wichita, KS", "Cloud County-Rural", "Republic County-Rural", "Jewell County-Rural",
  "Harper County-Rural", "Arkansas City-Winfield, KS", "Hutchinson, KS", "Pratt County-Rural",
  "Chautauqua County-Rural", "Kingman County-Rural", "Barber County-Rural", "Kiowa County-Rural",
  "Comanche County-Rural", "McPherson, KS", "Salina, KS", "Ellsworth County-Rural", "Rice County-Rural",
  "Osborne County-Rural", "Great Bend, KS", "Ness County-Rural", "Lane County-Rural", "Trego County-Rural",
  "Hodgeman County-Rural", "Stafford County-Rural", "Hays, KS", "Dodge City, KS", "Gove County-Rural",
  "Norton County-Rural", "Rooks County-Rural", "Rawlins County-Rural", "Thomas County-Rural",
  "Cheyenne County-Rural", "Sherman County-Rural", "Wallace County-Rural", "Garden City, KS", "Gray County-Rural",
  "Haskell County-Rural", "Meade County-Rural", "Kearny County-Rural", "Morton County-Rural",
  "Stanton County-Rural", "Liberal, KS", "Wichita County-Rural", "Greeley County-Rural", "Guymon, OK",
  "Cuming County-Rural", "Lincoln, NE", "Thurston County-Rural", "Fremont, NE", "Beatrice, NE",
  "Otoe County-Rural", "Thayer County-Rural", "York County-Rural", "Fillmore County-Rural",
  "Nuckolls County-Rural", "Richardson County-Rural", "Hastings, NE", "Columbus, NE", "Boone County-Rural",
  "Nance County-Rural", "Grand Island, NE", "Norfolk, NE", "Antelope County-Rural", "Dixon County-Rural",
  "Rock County-Rural", "Boyd County-Rural", "Keya Paha County-Rural", "Kearney, NE", "Loup County-Rural",
  "North Platte, NE", "Lexington, NE", "Phelps County-Rural", "Furnas County-Rural", "Frontier County-Rural",
  "Red Willow County-Rural", "Dundy County-Rural", "Chase County-Rural", "Hayes County-Rural",
  "Hitchcock County-Rural", "Arthur County-Rural", "Keith County-Rural", "Morrill County-Rural", "Scottsbluff, NE",
  "Kimball County-Rural", "Cherry County-Rural", "Garden County-Rural", "Hooker County-Rural",
  "Box Butte County-Rural", "Dawes County-Rural", "New Orleans-Metairie, LA", "Houma-Bayou Cane-Thibodaux, LA",
  "Baton Rouge, LA", "Lafayette, LA", "Morgan City, LA", "Hammond, LA", "Slidell-Mandeville-Covington, LA",
  "Bogalusa, LA", "Opelousas, LA", "New Iberia, LA", "Evangeline Parish-Rural", "Allen Parish-Rural",
  "Lake Charles, LA", "DeRidder, LA", "Vernon Parish-Rural", "Alexandria, LA", "Bienville Parish-Rural",
  "Claiborne Parish-Rural", "Ruston, LA", "Shreveport-Bossier City, LA", "Minden, LA", "Natchitoches, LA",
  "Red River Parish-Rural", "Winn Parish-Rural", "Sabine Parish-Rural", "Monroe, LA", "Franklin Parish-Rural",
  "Jackson Parish-Rural", "Madison Parish-Rural", "East Carroll Parish-Rural", "West Carroll Parish-Rural",
  "Avoyelles Parish-Rural", "Catahoula Parish-Rural", "La Salle Parish-Rural", "Tensas Parish-Rural",
  "Caldwell Parish-Rural", "Pine Bluff, AR", "Little Rock-North Little Rock-Conway, AR", "Bradley County-Rural",
  "Ashley County-Rural", "Chicot County-Rural", "Drew County-Rural", "Camden, AR", "Dallas County-Rural",
  "Nevada County-Rural", "El Dorado, AR", "Magnolia, AR", "Arkadelphia, AR", "Hempstead County-Rural",
  "Texarkana, TX-AR", "Sevier County-Rural", "Hot Springs, AR", "Malvern, AR", "Conway County-Rural",
  "Arkansas County-Rural", "Woodruff County-Rural", "Searcy, AR", "Batesville, AR", "Russellville, AR",
  "Blytheville, AR", "Forrest City, AR", "Cross County-Rural", "Jonesboro, AR", "Paragould, AR",
  "Sharp County-Rural", "Izard County-Rural", "Mountain Home, AR", "Fayetteville-Springdale-Rogers, AR",
  "Searcy County-Rural", "Fort Smith, AR-OK", "Oklahoma City, OK", "Caddo County-Rural", "Lawton, OK",
  "Weatherford, OK", "Kingfisher County-Rural", "Stillwater, OK", "Garvin County-Rural", "Shawnee, OK",
  "Duncan, OK", "Enid, OK", "Tulsa, OK", "Ardmore, OK", "Johnston County-Rural", "Love County-Rural",
  "Atoka County-Rural", "Durant, OK", "Altus, OK", "Greer County-Rural", "Tillman County-Rural",
  "Harmon County-Rural", "Elk City, OK", "Roger Mills County-Rural", "Major County-Rural", "Alfalfa County-Rural",
  "Woods County-Rural", "Woodward, OK", "Ellis County-Rural", "Beaver County-Rural", "Cimarron County-Rural",
  "Bartlesville, OK", "Okfuskee County-Rural", "Craig County-Rural", "Mayes County-Rural", "Nowata County-Rural",
  "Miami, OK", "Tahlequah, OK", "Muskogee, OK", "McAlester, OK", "Pushmataha County-Rural", "Coal County-Rural",
  "Hughes County-Rural", "Latimer County-Rural", "Le Flore County-Rural", "Ada, OK", "Ponca City, OK",
  "McCurtain County-Rural", "Dallas-Fort Worth-Arlington, TX", "Sherman-Denison, TX", "Corsicana, TX",
  "Van Zandt County-Rural", "Athens, TX", "Rains County-Rural", "Wood County-Rural", "Paris, TX", "Bonham, TX",
  "Delta County-Rural", "Sulphur Springs, TX", "Mount Pleasant, TX", "Longview, TX", "Tyler, TX",
  "Jacksonville, TX", "Palestine, TX", "Nacogdoches, TX", "Freestone County-Rural", "Leon County-Rural",
  "Limestone County-Rural", "Trinity County-Rural", "Huntsville, TX", "Lufkin, TX", "San Augustine County-Rural",
  "Sabine County-Rural", "Granbury, TX", "Waco, TX", "Somervell County-Rural", "Mineral Wells, TX",
  "Wichita Falls, TX", "Montague County-Rural", "Jack County-Rural", "Gainesville, TX", "Vernon, TX",
  "Throckmorton County-Rural", "Young County-Rural", "Baylor County-Rural", "Foard County-Rural",
  "Stephenville, TX", "Stephens County-Rural", "Shackelford County-Rural", "Brownwood, TX", "Eastland County-Rural",
  "Abilene, TX", "Mills County-Rural", "Coleman County-Rural", "Killeen-Temple, TX", "Milam County-Rural",
  "Austin-Round Rock-San Marcos, TX", "Burnet County-Rural", "College Station-Bryan, TX", "Runnels County-Rural",
  "San Saba County-Rural", "McCulloch County-Rural", "Llano County-Rural", "Concho County-Rural",
  "Menard County-Rural", "Schleicher County-Rural", "Kimble County-Rural", "San Angelo, TX",
  "Crockett County-Rural", "Reagan County-Rural", "Coke County-Rural", "Del Rio, TX", "Sterling County-Rural",
  "Sutton County-Rural", "Houston-Pasadena-The Woodlands, TX", "Grimes County-Rural", "Beaumont-Port Arthur, TX",
  "Colorado County-Rural", "Bay City, TX", "El Campo, TX", "Brenham, TX", "Port Lavaca, TX", "Victoria, TX",
  "Corpus Christi, TX", "Refugio County-Rural", "DeWitt County-Rural", "Gonzales County-Rural",
  "Lavaca County-Rural", "La Salle County-Rural", "San Antonio-New Braunfels, TX", "Frio County-Rural",
  "McMullen County-Rural", "Live Oak County-Rural", "Kerrville, TX", "Dimmit County-Rural", "Laredo, TX",
  "Real County-Rural", "Fredericksburg, TX", "Zapata, TX", "Blanco County-Rural", "Beeville, TX",
  "Karnes County-Rural", "Duval County-Rural", "Alice, TX", "Kenedy County-Rural", "Kingsville, TX",
  "Jim Hogg County-Rural", "McAllen-Edinburg-Mission, TX", "Brownsville-Harlingen, TX",
  "Rio Grande City-Roma, TX", "Raymondville, TX", "Uvalde, TX", "Zavala County-Rural", "Kinney County-Rural",
  "Terrell County-Rural", "Eagle Pass, TX", "Hereford, TX", "Amarillo, TX", "Lipscomb County-Rural",
  "Ochiltree County-Rural", "Borger, TX", "Parmer County-Rural", "Hemphill County-Rural", "Dumas, TX",
  "Hartley County-Rural", "Plainview, TX", "Dallam County-Rural", "Castro County-Rural", "Lamb County-Rural",
  "Donley County-Rural", "Pampa, TX", "Hansford County-Rural", "Swisher County-Rural", "Collingsworth County-Rural",
  "Briscoe County-Rural", "Childress County-Rural", "Cottle County-Rural", "Motley County-Rural",
  "Dickens County-Rural", "Hall County-Rural", "Lubbock, TX", "King County-Rural", "Terry County-Rural",
  "Gaines County-Rural", "Yoakum County-Rural", "Bailey County-Rural", "Midland, TX", "Borden County-Rural",
  "Stonewall County-Rural", "Sweetwater, TX", "Big Spring, TX", "Snyder, TX", "Fisher County-Rural",
  "Andrews, TX", "Town of Pecos, TX", "Ward County-Rural", "Glasscock County-Rural", "Pecos County-Rural",
  "Crane County-Rural", "Upton County-Rural", "Brewster County-Rural", "Odessa, TX", "Winkler County-Rural",
  "Loving County-Rural", "Culberson County-Rural", "El Paso, TX", "Alamogordo, NM", "Presidio County-Rural",
  "Denver-Aurora-Centennial, CO", "Boulder, CO", "Colorado Springs, CO", "Edwards, CO", "Grand County-Rural",
  "Breckenridge, CO", "Steamboat Springs, CO", "Chaffee County-Rural", "Fort Collins-Loveland, CO", "Greeley, CO",
  "Fort Morgan, CO", "Sterling, CO", "Yuma County-Rural", "Sedgwick County-Rural", "Kit Carson County-Rural",
  "Cañon City, CO", "Pueblo, CO", "Las Animas County-Rural", "Baca County-Rural", "Otero County-Rural",
  "Crowley County-Rural", "Bent County-Rural", "Huerfano County-Rural", "Prowers County-Rural", "Alamosa, CO",
  "Archuleta County-Rural", "Durango, CO", "Rio Grande County-Rural", "Saguache County-Rural",
  "Hinsdale County-Rural", "Mineral County-Rural", "Farmington, NM", "Gunnison County-Rural", "Montrose, CO",
  "San Juan County-Rural", "Dolores County-Rural", "Montezuma County-Rural", "San Miguel County-Rural",
  "Ouray County-Rural", "Grand Junction, CO", "Rifle, CO", "Rio Blanco County-Rural", "Cheyenne, WY",
  "Laramie, WY", "Carbon County-Rural", "Cody, WY", "Jackson, WY-ID", "Platte County-Rural",
  "Goshen County-Rural", "Niobrara County-Rural", "Converse County-Rural", "Riverton, WY", "Rock Springs, WY",
  "Hot Springs County-Rural", "Washakie County-Rural", "Casper, WY", "Weston County-Rural", "Gillette, WY",
  "Sheridan, WY", "Sublette County-Rural", "Heber, UT", "Evanston, WY-UT", "Caribou County-Rural", "Pocatello, ID",
  "Blackfoot, ID", "Power County-Rural", "Burley, ID", "Brigham City, UT-ID", "Idaho Falls, ID",
  "Bear Lake County-Rural", "Lemhi County-Rural", "Logan, UT-ID", "Twin Falls, ID", "Boise City, ID", "Hailey, ID",
  "Gooding County-Rural", "Mountain Home, ID", "Rexburg, ID", "Lewiston, ID-WA", "Moscow, ID", "Ontario, OR-ID",
  "Sandpoint, ID", "Coeur d'Alene, ID", "Shoshone County-Rural", "Boundary County-Rural", "Benewah County-Rural",
  "Duchesne County-Rural", "Provo-Orem-Lehi, UT", "Salt Lake City-Murray, UT", "Ogden, UT",
  "Daggett County-Rural", "Vernal, UT", "White Pine County-Rural", "Price, UT", "Emery County-Rural",
  "Apache County-Rural", "Kane County-Rural", "Show Low, AZ", "Sanpete County-Rural", "Millard County-Rural",
  "Piute County-Rural", "Cedar City, UT", "St. George, UT", "Phoenix-Mesa-Chandler, AZ", "Payson, AZ",
  "Prescott Valley-Prescott, AZ", "Tucson, AZ", "La Paz County-Rural", "Yuma, AZ",
  "Lake Havasu City-Kingman, AZ", "Safford, AZ", "Greenlee County-Rural", "Sierra Vista-Douglas, AZ",
  "Nogales, AZ", "Flagstaff, AZ", "Gallup, NM", "Albuquerque, NM", "Cibola County-Rural", "Socorro County-Rural",
  "Santa Fe, NM", "Ruidoso, NM", "Española, NM", "Las Vegas, NM", "Taos, NM", "Los Alamos, NM",
  "Colfax County-Rural", "Guadalupe County-Rural", "Catron County-Rural", "Sierra County-Rural", "Las Cruces, NM",
  "Hidalgo County-Rural", "Silver City, NM", "Deming, NM", "Clovis, NM", "Hobbs, NM", "Roswell, NM",
  "De Baca County-Rural", "Quay County-Rural", "Carlsbad-Artesia, NM", "Pahrump, NV",
  "Las Vegas-Henderson-North Las Vegas, NV", "Mono County-Rural", "Esmeralda County-Rural", "Bishop, CA",
  "Riverside-San Bernardino-Ontario, CA", "Lander County-Rural", "Elko, NV", "Reno, NV", "Winnemucca, NV",
  "Pershing County-Rural", "Fallon, NV", "Gardnerville Ranchos, NV-CA", "Carson City, NV",
  "Los Angeles-Long Beach-Anaheim, CA", "Oxnard-Thousand Oaks-Ventura, CA", "San Diego-Chula Vista-Carlsbad, CA",
  "El Centro, CA", "Santa Maria-Santa Barbara, CA", "Hanford-Corcoran, CA", "Visalia, CA", "Bakersfield-Delano, CA",
  "Fresno, CA", "Salinas, CA", "San Jose-Sunnyvale-Santa Clara, CA", "San Luis Obispo-Paso Robles, CA",
  "Mariposa County-Rural", "Merced, CA", "San Francisco-Oakland-Fremont, CA", "Napa, CA", "Vallejo, CA",
  "Santa Rosa-Petaluma, CA", "Sacramento-Roseville-Folsom, CA", "Santa Cruz-Watsonville, CA", "Stockton-Lodi, CA",
  "Calaveras County-Rural", "Sonora, CA", "Modesto, CA", "Ukiah, CA", "Clearlake, CA", "Eureka-Arcata, CA",
  "Crescent City, CA", "Siskiyou County-Rural", "Amador County-Rural", "Truckee-Grass Valley, CA", "Yuba City, CA",
  "Colusa County-Rural", "Chico, CA", "Plumas County-Rural", "Glenn County-Rural", "Red Bluff, CA", "Redding, CA",
  "Susanville, CA", "Modoc County-Rural", "Urban Honolulu, HI", "Kapaa, HI", "Hilo-Kailua, HI",
  "Kahului-Wailuku, HI", "The Dalles, OR", "Portland-Vancouver-Hillsboro, OR-WA", "Salem, OR", "Hood River, OR",
  "Astoria, OR", "Tillamook County-Rural", "Corvallis, OR", "Albany, OR", "Eugene-Springfield, OR", "Newport, OR",
  "Brookings, OR", "Roseburg, OR", "Coos Bay-North Bend, OR", "Medford, OR", "Grants Pass, OR",
  "Klamath Falls, OR", "Bend, OR", "Harney County-Rural", "Hermiston-Pendleton, OR", "Gilliam County-Rural",
  "Baker City, OR", "La Grande, OR", "Wallowa County-Rural", "Seattle-Tacoma-Bellevue, WA", "Ellensburg, WA",
  "Bremerton-Silverdale-Port Orchard, WA", "Bellingham, WA", "Mount Vernon-Anacortes, WA", "Oak Harbor, WA",
  "Centralia, WA", "Port Angeles, WA", "Port Townsend, WA", "Olympia-Lacey-Tumwater, WA", "Aberdeen, WA",
  "Shelton, WA", "Pacific County-Rural", "Longview-Kelso, WA", "Klickitat County-Rural", "Wahkiakum County-Rural",
  "Wenatchee-East Wenatchee, WA", "Okanogan County-Rural", "Moses Lake, WA", "Othello, WA", "Yakima, WA",
  "Kennewick-Richland, WA", "Spokane-Spokane Valley, WA", "Pullman, WA", "Pend Oreille County-Rural",
  "Ferry County-Rural", "Walla Walla, WA", "Columbia County-Rural", "Anchorage, AK", "Bethel Census Area-Rural",
  "North Slope Borough-Rural", "Aleutians West Census Area-Rural", "Lake and Peninsula Borough-Rural",
  "Kodiak Island Borough-Rural", "Aleutians East Borough-Rural", "Wade Hampton Census Area-Rural",
  "Dillingham Census Area-Rural", "Kenai Peninsula Borough-Rural", "Yukon-Koyukuk Census Area-Rural",
  "Valdez-Cordova Census Area-Rural", "Bristol Bay Borough-Rural", "Nome Census Area-Rural",
  "Yakutat City and Borough-Rural", "Fairbanks-College, AK", "Denali Borough-Rural",
  "Southeast Fairbanks Census Area-Rural", "Northwest Arctic Borough-Rural", "Juneau, AK",
  "Hoonah-Angoon Census Area-Rural", "Haines Borough-Rural", "Petersburg Census Area-Rural",
  "Sitka City and Borough-Rural", "Skagway Municipality-Rural", "Ketchikan, AK",
  "Prince of Wales-Hyder Census Area-Rural", "Wrangell City and Borough-Rural"
];
